import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    DATABASE_URL: z.string().url(),
    GOOGLE_CLIENT_ID: z.string().min(1),
    GOOGLE_CLIENT_SECRET: z.string().min(1),
    BREVO_API_KEY: z.string().min(1),
    SOKETI_APP_ID: z.string().min(1),
    SOKETI_KEY: z.string().min(1),
    SOKETI_SECRET: z.string().min(1),
    SOKETI_HOST: z.string().min(1),
    SOKETI_PORT: z.string().min(1),
    SOKETI_USE_TLS: z.enum(["true", "false"]),
    NEXTAUTH_SECRET: z.string().min(1),
    NEXTAUTH_URL: z.string().url(),
    APP_URL: z.string().url().optional(),
    BREVO_SENDER_EMAIL: z.string().email().optional(),
  },
  client: {
    NEXT_PUBLIC_SOKETI_KEY: z.string().min(1),
    NEXT_PUBLIC_SOKETI_HOST: z.string().min(1),
    NEXT_PUBLIC_SOKETI_PORT: z.string().min(1),
    NEXT_PUBLIC_SOKETI_USE_TLS: z.enum(["true", "false"]),
    NEXT_PUBLIC_APP_URL: z.string().url().optional(),
  },
  runtimeEnv: {
    DATABASE_URL: process.env.DATABASE_URL,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    BREVO_API_KEY: process.env.BREVO_API_KEY,
    SOKETI_APP_ID: process.env.SOKETI_APP_ID,
    SOKETI_KEY: process.env.SOKETI_KEY,
    SOKETI_SECRET: process.env.SOKETI_SECRET,
    SOKETI_HOST: process.env.SOKETI_HOST,
    SOKETI_PORT: process.env.SOKETI_PORT,
    SOKETI_USE_TLS: process.env.SOKETI_USE_TLS,
    NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
    NEXTAUTH_URL: process.env.NEXTAUTH_URL,
    APP_URL: process.env.APP_URL,
    BREVO_SENDER_EMAIL: process.env.BREVO_SENDER_EMAIL,
    NEXT_PUBLIC_SOKETI_KEY: process.env.NEXT_PUBLIC_SOKETI_KEY,
    NEXT_PUBLIC_SOKETI_HOST: process.env.NEXT_PUBLIC_SOKETI_HOST,
    NEXT_PUBLIC_SOKETI_PORT: process.env.NEXT_PUBLIC_SOKETI_PORT,
    NEXT_PUBLIC_SOKETI_USE_TLS: process.env.NEXT_PUBLIC_SOKETI_USE_TLS,
    NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
  emptyStringAsUndefined: true,
});
